name: Project Build

on: [push]

jobs:
  build-server:
    strategy:
      matrix:
        version:
          - 8.0.x
        os: 
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet ${{ matrix.version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.version}}
      - name: Build Game Server
        run: make build-server
      - name: Build Game Client
        run: make build-client

